In [4]:
import numpy as np


In [5]:
#Calculating the inverse of a 2x2 matrix without using numpy

In [6]:
def get_M_Inv(m):
    if len(m) == 2:
        determinant = m[0][0]*m[1][1]-m[0][1]*m[1][0]
    
    #special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]


In [7]:
m2 = np.array([[5,12],[-3,0]])

get_M_Inv(m2)

[[0.0, -0.3333333333333333], [0.08333333333333333, 0.1388888888888889]]

In [8]:
#to check

In [9]:
np.linalg.inv(m2)

array([[ 0.        , -0.33333333],
       [ 0.08333333,  0.13888889]])

In [10]:
#Code a function to calculate the determinant of 2x2 matrix

In [11]:
def get_M_Det(m):
    #for 2x2 matrix
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]


In [12]:
m2 = np.array([[5,12],[-3,0]])

In [13]:
get_M_Det(m2)

36

In [14]:
#to check

In [15]:
np.linalg.det(m2)

36.0

In [20]:
#Code a function that interchange the diagonal elements of a 2x2 matrix and
#         inverse the sign of the off diagonal elements


In [21]:
m22 = np.array([[5,12],[-3,0]])

In [22]:
def inter_Change(m):
    m[0,0] , m[1,1] = m[1,1] , m[0,0]
    
    m[0,1] = -m[0,1]
    
    m[1,0] = -m[1,0]
    
    return m

In [23]:
#Code a function to compute the inverse of 2x2 matrix based on the two previous
#        functions if it exists

In [24]:
 def get_M_Inv2(m):

    return inter_Change(m)/get_M_Det(m)

In [25]:
m22 = np.array([[5,12],[-3,0]])
get_M_Inv2(m22)

array([[ 0.        , -0.33333333],
       [ 0.08333333,  0.13888889]])

In [26]:
#to check

In [27]:
m22 = np.array([[5,12],[-3,0]])
np.linalg.inv(m22)

array([[ 0.        , -0.33333333],
       [ 0.08333333,  0.13888889]])

In [45]:
#Coding a function that generates the matrix of minors of a 3x3 matrix

In [59]:
def matrixOfMinors(m):
    
    mat_of_minors = np.array([[0,0,0],[0,0,0],[0,0,0]])
    
   
    x = m[1][1] * m[2][2]
    y = m[1][2] * m[2][1]
    
    mat_of_minors[0][0] = x - y
    
    x = m[1][0] * m[2][2]
    y = m[2][0] * m[1][2]
    
    mat_of_minors[0][1] = x - y
    
    x = m[1][0] * m[2][1]
    y = m[1][1] * m[2][0]
    
    mat_of_minors[0][2] = x - y
    
    x = m[0][1] * m[2][2]
    y = m[0][2] * m[2][1]
    
    mat_of_minors[1][0] = x - y
    
    x = m[0][0] * m[2][2]
    y = m[0][2] * m[2][0]
    
    mat_of_minors[1][1] = x - y
    
    x = m[0][0] * m[2][1]
    y = m[0][1] * m[2][0]
    
    mat_of_minors[1][2] = x - y
    
    x = m[0][1] * m[1][2]
    y = m[0][2] * m[1][1]
    
    mat_of_minors[2][0] = x - y
    
    x = m[0][0] * m[1][2]
    y = m[0][2] * m[1][0]
    
    mat_of_minors[2][1] = x - y
    
    x = m[1][1] * m[0][0]
    y = m[1][0] * m[0][1]
    
    mat_of_minors[2][2] = x - y
    
    return mat_of_minors
    
    

In [60]:
m333 = np.array([[3,0,2],[2,0,-2],[0,1,1]])

matrixOfMinors(m333)


array([[  2,   2,   2],
       [ -2,   3,   3],
       [  0, -10,   0]])

In [ ]:
#Coding a function that generates the matrix of cofactors of a 3x3 matrix

In [63]:
def matrixOfcofactors(m):
    m = matrixOfMinors(m333)
    
    m[0][1] *= -1
    m[1][0] *= -1
    m[1][2] *= -1
    m[2][1] *= -1
    
    return m

In [64]:
matrixOfcofactors(m333)

array([[ 2, -2,  2],
       [ 2,  3, -3],
       [ 0, 10,  0]])

In [ ]:
#Coding a function that generates the transpose of a 3x3 matrix

In [65]:
def Adjoint(m):
    m = matrixOfcofactors(m)
    
    m[0][1] , m[1][0] = m[1][0],  m[0][1]
    
    m[0][2] , m[2][0] = m[2][0],  m[0][2]
    
    m[1][2] , m[2][1] = m[2][1],  m[1][2]
    
    return m

In [66]:
Adjoint(m333)

array([[ 2,  2,  0],
       [-2,  3, 10],
       [ 2, -3,  0]])

In [71]:
def Determinant(m):
    m2 = matrixOfcofactors(m)
    
    det = m[0][0] * m2[0][0] + m[0][1] * m2[0][1] + m[0][2] * m2[0][2] 
    
    return det

In [72]:
Determinant(m333)

10

In [ ]:
#Coding a function that checks if a 3x3 matrix is invertible

In [77]:
def invertible(m):
    det = Determinant(m)
    if det != 0:
        return True
    else: return False

In [78]:
invertible(m333)

True

In [73]:
def get_inv(m):
    
    if !(invertible(m)):
        break
    return Adjoint(m)/Determinant(m)

In [89]:
m333 = np.array([[3,0,2],[2,0,-2],[0,1,1]])
get_inv(m333)

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3,  0. ]])

In [90]:
#to check 

In [91]:
np.linalg.inv(m333)

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])